import type { Metadata } from "next";
import { sourceSans3 } from "./fonts";
import "./globals.css";
import { Toaster } from "react-hot-toast"
import "leaflet/dist/leaflet.css";

export const metadata: Metadata = {
  title: "Nepal Saathi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sourceSans3.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col ">
        <Toaster position="top-center"/>{children}
      </body>
    </html>
  );
}
